# Generated by Django 4.2.2 on 2023-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_productspecification_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='specification',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(related_name='products', to='store.productspecification'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='specification_values',
            field=models.ManyToManyField(related_name='specifications', to='store.productspecificationvalue'),
        ),
    ]
