# Generated by Django 4.2.2 on 2023-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_productspecification_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='specification_values',
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='specifications',
            field=models.ManyToManyField(related_name='specification_values', to='store.productspecification'),
        ),
    ]
