# Generated by Django 4.2.2 on 2023-06-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_productspecification_specification_values_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecificationvalue',
            name='specifications',
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='specification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification_values', to='store.productspecification'),
        ),
    ]
