# Generated by Django 4.2.2 on 2023-06-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='specifications',
        ),
    ]
