# Generated by Django 4.2.2 on 2023-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_productvariant_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='specifications',
            field=models.ManyToManyField(related_name='variants', to='store.specificationvalue'),
        ),
    ]
